### ISSUE TITLE
[Bug]: No module named 'Bard

### ISSUE THREAD

**Issue by liuguofeng-java** [XiaoXinYo/Chat-WebAPI#2]
### 在提交前请确保以下这些

- [X] ChatGPT,EdgeGPT,BingImageCreator,GoogleBard,easy-ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Windows

### Python版本

3.9

### 问题

![image](https://github.com/XiaoXinYo/Chat-API/assets/59218624/78d70348-32a1-4774-90d0-337fc3ea2ad2)
不知道为什么提示 ‘ModuleNotFoundError: No module named 'Bard'’

### 触发

安装依赖时

**Comment by ykaiqx** [comment]
安装GoogleBard了吗？

**Comment by liuguofeng-java** [comment]
GoogleBard是啥 我直接 pip install Bard 没有反应

**Comment by ykaiqx** [comment]
pip install&nbsp;GoogleBard




GoogleBard是 bard在pypi上的名字



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 一马平川 ***@***.***&gt;
发送时间: 2023年5月26日 22:40
收件人: XiaoXinYo/Chat-API ***@***.***&gt;
抄送: XiaoXinYo ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [XiaoXinYo/Chat-API] [Bug]: 报错 (Issue #2)





 
GoogleBard是啥 我直接 pip install Bard 没有反应
